server:
  servlet:
    context-path: /roerdev-api
  port : 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update, none)
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      mode: always
      continue-on-error: true
swagger:
  enabled: true
send-email:
  from: javatechsol@yopmail.com
  apikey: YOUR_API_KEY_SENDGRID

